# Generated by Django 5.0.4 on 2024-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all/about/')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='all/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='video',
            field=models.FileField(upload_to='all/products/'),
        ),
    ]
